// Adapted from midnightntwrk/example-bboard.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * This file is the main driver for the Midnight PayVeil example.
 * The entry point is the run function, at the end of the file.
 * We expect the startup files (testnet-remote.ts, standalone.ts, etc.) to
 * call run with some specific configuration that sets the network addresses
 * of the servers this file relies on.
 */

import { createInterface, type Interface } from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { WebSocket } from 'ws';
import {
  PayVeilAPI,
  type PayVeilDerivedState,
  payveilPrivateStateKey,
  type PayVeilProviders,
  type DeployedPayVeilContract,
  type PrivateStateId,
} from '../../api/src/index';
import { type WalletFacade } from '@midnight-ntwrk/wallet-sdk-facade';
import { ledger, type Ledger } from '../../contract/src/managed/payveil/contract/index.js';
import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { type Logger } from 'pino';
import { type Config, StandaloneConfig } from './config.js';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import { type ContractAddress } from '@midnight-ntwrk/midnight-js-protocol/compact-runtime';
import { assertIsContractAddress, toHex } from '@midnight-ntwrk/midnight-js-utils';
import { TestEnvironment } from '@midnight-ntwrk/testkit-js';
import { MidnightWalletProvider } from './midnight-wallet-provider';
import { randomBytes } from '../../api/src/utils';
import { unshieldedToken } from '@midnight-ntwrk/midnight-js-protocol/ledger';
import { syncWallet, waitForUnshieldedFunds } from './wallet-utils';
import { generateDust } from './generate-dust';
import { PayVeilPrivateState } from '../../contract/src/witnesses.js';

// @ts-expect-error: It's needed to enable WebSocket usage through apollo
globalThis.WebSocket = WebSocket;

/* **********************************************************************
 * getPayVeilLedgerState: a helper that queries the current state of
 * the data on the ledger, for a specific PayVeil contract.
 * Note that the Ledger type returned here is not some generic,
 * abstract ledger object, but specifically the type generated by
 * the Compact compiler to correspond to the ledger declaration
 * in the PayVeil contract.
 */

export const getPayVeilLedgerState = async (
  providers: PayVeilProviders,
  contractAddress: ContractAddress,
): Promise<Ledger | null> => {
  assertIsContractAddress(contractAddress);
  const contractState = await providers.publicDataProvider.queryContractState(contractAddress);
  return contractState != null ? ledger(contractState.data) : null;
};
// providers.publicDataProvider
//   .queryContractState(contractAddress)
//   .then((contractState) => (contractState != null ? ledger(contractState.data) : null));

/* **********************************************************************
 * deployOrJoin: returns a contract, by prompting the user about
 * whether to deploy a new one or join an existing one and then
 * calling the appropriate helper.
 */

const DEPLOY_OR_JOIN_QUESTION = `
You can do one of the following:
  1. Deploy a new PayVeil contract
  2. Join an existing PayVeil contract
  3. Exit
Which would you like to do? `;

const deployOrJoin = async (providers: PayVeilProviders, rli: Interface, logger: Logger): Promise<PayVeilAPI | null> => {
  let api: PayVeilAPI | null = null;

  while (true) {
    const choice = await rli.question(DEPLOY_OR_JOIN_QUESTION);
    switch (choice) {
      case '1':
        api = await PayVeilAPI.deploy(providers, logger);
        logger.info(`Deployed contract at address: ${api.deployedContractAddress}`);
        return api;
      case '2':
        api = await PayVeilAPI.join(providers, await rli.question('What is the contract address (in hex)? '), logger);
        logger.info(`Joined contract at address: ${api.deployedContractAddress}`);
        return api;
      case '3':
        logger.info('Exiting...');
        return null;
      default:
        logger.error(`Invalid choice: ${choice}`);
    }
  }
};

/* **********************************************************************
 * displayLedgerState: shows the values of each of the fields declared
 * by the contract to be in the ledger state of the PayVeil app.
 */

const displayLedgerState = async (
  providers: PayVeilProviders,
  deployedPayVeilContract: DeployedPayVeilContract,
  logger: Logger,
): Promise<void> => {
  const contractAddress = deployedPayVeilContract.deployTxData.public.contractAddress;
  const ledgerState = await getPayVeilLedgerState(providers, contractAddress);
  if (ledgerState === null) {
    logger.info(`There is no PayVeil contract deployed at ${contractAddress}`);
  } else {
    const average = ledgerState.submissionCount > 0n ? ledgerState.totalSalary / ledgerState.submissionCount : undefined;
    logger.info(`Submission count is: ${ledgerState.submissionCount}`);
    logger.info(`Total salary (sum) is: ${ledgerState.totalSalary}`);
    logger.info(`Average salary is: ${average === undefined ? 'n/a (no submissions yet)' : average}`);
  }
};

/* **********************************************************************
 * displayPrivateState: shows the hex-formatted value of the local secret ID.
 */

const displayPrivateState = async (providers: PayVeilProviders, logger: Logger): Promise<void> => {
  const privateState = await providers.privateStateProvider.get(payveilPrivateStateKey);
  if (privateState === null) {
    logger.info(`There is no existing PayVeil private state`);
  } else {
    logger.info(`Current secret ID is: ${toHex(privateState.secretId)}`);
    logger.info(`Last salary held locally is: ${privateState.salary}`);
  }
};

/* **********************************************************************
 * displayDerivedState: shows the values of derived state which is made
 * by combining the ledger state with private state. Here, the derived
 * state checks whether this identity's nullifier is already a member of
 * the public `submitted` set, without ever revealing the identity itself.
 */

const displayDerivedState = (state: PayVeilDerivedState | undefined, logger: Logger) => {
  if (state === undefined) {
    logger.info(`No PayVeil state currently available`);
  } else {
    logger.info(`Submission count is: ${state.submissionCount}`);
    logger.info(`Total salary (sum) is: ${state.totalSalary}`);
    logger.info(`Average salary is: ${state.averageSalary === undefined ? 'n/a (no submissions yet)' : state.averageSalary}`);
    logger.info(`Has this identity already submitted? '${state.hasSubmitted ? 'yes' : 'no'}'`);
  }
};

/* **********************************************************************
 * mainLoop: the main interactive menu of the PayVeil app CLI.
 * Before starting the loop, the user is prompted to deploy a new
 * contract or join an existing one.
 */

const MAIN_LOOP_QUESTION = `
You can do one of the following:
  1. Submit a salary (privately)
  2. Display the current ledger state (known by everyone)
  3. Display the current private state (known only to this DApp instance)
  4. Display the current derived state (known only to this DApp instance)
  5. Exit
Which would you like to do? `;

const mainLoop = async (providers: PayVeilProviders, rli: Interface, logger: Logger): Promise<void> => {
  const payveilApi = await deployOrJoin(providers, rli, logger);
  if (payveilApi === null) {
    return;
  }
  let currentState: PayVeilDerivedState | undefined;
  const stateObserver = {
    next: (state: PayVeilDerivedState) => (currentState = state),
  };
  const subscription = payveilApi.state$.subscribe(stateObserver);
  try {
    while (true) {
      const choice = await rli.question(MAIN_LOOP_QUESTION);
      try {
        switch (choice) {
          case '1': {
            const salaryInput = await rli.question(`What is your salary (whole number, kept private)? `);
            await payveilApi.submitSalary(BigInt(salaryInput));
            break;
          }
          case '2':
            await displayLedgerState(providers, payveilApi.deployedContract, logger);
            break;
          case '3':
            await displayPrivateState(providers, logger);
            break;
          case '4':
            displayDerivedState(currentState, logger);
            break;
          case '5':
            logger.info('Exiting...');
            return;
          default:
            logger.error(`Invalid choice: ${choice}`);
        }
      } catch (e) {
        logError(logger, e);
        logger.info('Returning to main menu...');
      }
    }
  } finally {
    // While we allow errors to bubble up to the 'run' function, we will always need to dispose of the state
    // subscription when we exit.
    subscription.unsubscribe();
  }
};

/* ***********************************************************************
 * This seed gives access to tokens minted in the genesis block of a local development node - only
 * used in standalone networks to build a wallet with initial funds.
 */
const GENESIS_MINT_WALLET_SEED = '0000000000000000000000000000000000000000000000000000000000000001';

/* **********************************************************************
 * buildWallet: unless running in a standalone (offline) mode,
 * prompt the user to tell us whether to create a new wallet
 * or recreate one from a prior seed.
 */

const WALLET_LOOP_QUESTION = `
You can do one of the following:
  1. Build a fresh wallet
  2. Build wallet from a seed
  3. Exit
Which would you like to do? `;

const buildWallet = async (config: Config, rli: Interface, logger: Logger): Promise<string | undefined> => {
  if (config instanceof StandaloneConfig) {
    return GENESIS_MINT_WALLET_SEED;
  }
  while (true) {
    const choice = await rli.question(WALLET_LOOP_QUESTION);
    switch (choice) {
      case '1':
        return toHex(randomBytes(32));
      case '2':
        return await rli.question('Enter your wallet seed: ');
      case '3':
        logger.info('Exiting...');
        return undefined;
      default:
        logger.error(`Invalid choice: ${choice}`);
    }
  }
};

/* **********************************************************************
 * run: the main entry point that starts the whole PayVeil CLI.
 *
 * If called with a Docker environment argument, the application
 * will wait for Docker to be ready before doing anything else.
 */

export const run = async (config: Config, testEnv: TestEnvironment, logger: Logger): Promise<void> => {
  const rli = createInterface({ input, output, terminal: true });
  const providersToBeStopped: MidnightWalletProvider[] = [];
  try {
    const envConfiguration = await testEnv.start();
    logger.info(`Environment started with configuration: ${JSON.stringify(envConfiguration)}`);
    const seed = await buildWallet(config, rli, logger);
    if (seed === undefined) {
      return;
    }
    const walletProvider = await MidnightWalletProvider.build(logger, envConfiguration, seed);
    providersToBeStopped.push(walletProvider);
    const walletFacade: WalletFacade = walletProvider.wallet;

    await walletProvider.start();

    const unshieldedState = await waitForUnshieldedFunds(
      logger,
      walletFacade,
      envConfiguration,
      unshieldedToken(),
      config.generateDust,
    );
    const nightBalance = unshieldedState.balances[unshieldedToken().raw];
    if (nightBalance === undefined) {
      logger.info('No funds received, exiting...');
      return;
    }
    logger.info(`Your NIGHT wallet balance is: ${nightBalance}`);

    if (config.generateDust) {
      const dustGeneration = await generateDust(logger, seed, unshieldedState, walletFacade);
      if (dustGeneration) {
        logger.info(`Submitted dust generation registration transaction: ${dustGeneration}`);
        await syncWallet(logger, walletFacade);
      }
    }

    const zkConfigProvider = new NodeZkConfigProvider<'submitSalary'>(config.zkConfigPath);
    const providers: PayVeilProviders = {
      privateStateProvider: levelPrivateStateProvider<PrivateStateId, PayVeilPrivateState>({
        privateStateStoreName: config.privateStateStoreName,
        signingKeyStoreName: `${config.privateStateStoreName}-signing-keys`,
        privateStoragePasswordProvider: () => {
          return 'PayVeil-Test-2026!';
        },
        accountId: seed,
      }),
      publicDataProvider: indexerPublicDataProvider(envConfiguration.indexer, envConfiguration.indexerWS),
      zkConfigProvider: zkConfigProvider,
      proofProvider: httpClientProofProvider(envConfiguration.proofServer, zkConfigProvider),
      walletProvider: walletProvider,
      midnightProvider: walletProvider,
    };
    await mainLoop(providers, rli, logger);
  } catch (e) {
    logError(logger, e);
    logger.info('Exiting...');
  } finally {
    try {
      rli.close();
      rli.removeAllListeners();
    } catch (e) {
      logError(logger, e);
    } finally {
      try {
        for (const wallet of providersToBeStopped) {
          logger.info('Stopping wallet...');
          await wallet.stop();
        }
        if (testEnv) {
          logger.info('Stopping test environment...');
          await testEnv.shutdown();
        }
      } catch (e) {
        logError(logger, e);
      }
    }
  }
};

function logError(logger: Logger, e: unknown) {
  if (e instanceof Error) {
    logger.error(`Found error '${e.message}'`);
    logger.debug(`${e.stack}`);
  } else {
    logger.error(`Found error (unknown type)`);
  }
}
